id: P3FCC84DA
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: de
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    bd2884a17c6b478f8ae1ce91fc23da3d:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    241268fb632a49d58fefb831da4c7654:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    26cda287d81740be99e1a78d4119c8a0:
      title: The Five Wisdoms
      parent: Dzogchen
    18dd39578b9545029ef65eca1a0173e7:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    8a3819e6c14841a8a9a387026d385ffb:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    879975a2a7b7406a831da82fae38491c:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    27c60369d4164f6f94e2cdbccd8bd5fc:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    895fc07313974a41933abc6036bce631:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    592576e7a7fb48a8a7709a7fcf5c607f:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.757591'
last_modified_at: '2022-03-01T00:22:24.757595'
